version: '3'
services:
    api:
        build:
            context: api
            dockerfile: Dockerfile
        expose: 
            - 80:80
    curl-test:
        image: curl-test
        build:
            context: curl-test
            dockerfile: Dockerfile
        depends_on: 
            - api
        links: 
            - api
        tty: true
    network-test:
        build:
            context: network-test
        depends_on: 
            - api
        links: 
            - api