version: '3'
services:
    api:
        build:
            context: api
            dockerfile: Dockerfile
        ports: 
            - 3000:3000
    curl-test:
        image: curl-test
        build:
            context: curl-test
            dockerfile: Dockerfile
        depends_on: 
            - api
        links: 
            - api
        tty: true
    network-test:
        build:
            context: network-test
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on: 
            - api
        links: 
            - api